### ISSUE TITLE
create_document self.r_session.post( AttributeError: 'NoneType' object has no attribute 'post'

### ISSUE THREAD

**Issue by csbrandt** [cloudant/python-cloudant#410]
## Bug Description

`create_document(record)` fails with error while using `couchdb_admin_party`  context helper when accessing outside of context.

### 1. Steps to reproduce and the simplest code sample possible to demonstrate the issue

```
with couchdb_admin_party(url='http://localhost:5984') as client:
   try:
      couch = client.create_database(dbname='pipeline-artifacts', throw_on_exists=True)
   except CloudantClientException:
      couch = client['pipeline-artifacts']

couch.create_document({'Previous Day Open Interest': 1515.0, 'Volume': 140.0, 'Open': 205.0, 'Last': 201.0, 'symbol': 'LB', 'High': 206.0, 'Settle': 201.0, 'date': '2010-01-04', 'Low': 201.0})
```

### 2. What you expected to happen

Document should be created in database.

### 3. What actually happened

This operation raises the following error,

```
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/builds/jobs.py", line 42, in download
    couch.create_document(record)
  File "/usr/local/lib/python3.5/site-packages/cloudant/database.py", line 161, in create_document
    doc.create()
  File "/usr/local/lib/python3.5/site-packages/cloudant/document.py", line 147, in create
    resp = self.r_session.post(
AttributeError: 'NoneType' object has no attribute 'post'
```

## Environment details
- Version(s) that are affected by this issue.
    > 2.10.0
- Python version
    > 3.5

**Comment by csbrandt** [comment]
Currently I was able to solve the issue by not using the `couchdb_admin_party` context helper, the following is equivalent and removes the issue of losing the session outside of the context helper.

```
client = CouchDB(None, None, url='http://localhost:5984', admin_party=True, connect=True)
```
