### ISSUE TITLE
Don't make the fields argument required for a Query

### ISSUE THREAD

**Issue by JanekLehr** [cloudant/python-cloudant#86]
Currently a python-cloudant query requires the user to pass in a list of fields in the `fields` parameter, but Cloudant does not require this parameter to be passed. Cloudant will default to returning all fields of a document if `fields` is not specified. Could python-cloudant be changed to mimic this behavior?

https://github.com/cloudant/python-cloudant/blob/master/src/cloudant/query.py#L185

**Comment by alfinkel** [comment]
Looks like that is a bug for sure.  We'll get that fixed.  Thanks.

**Comment by JanekLehr** [comment]
@alfinkel 
I'm writing a fix for this but I don't know how I should be running the test suites. I'm trying to run just the unit tests but I'm running into issues because I don't have a CouchDB instance running locally. Are the unit tests making real connections to a DB? Here's the stack trace from the `setUpClass`:
```
Error
Traceback (most recent call last):
  File "/Users/janeklehr/Development/python-cloudant/venv/lib/python2.7/site-packages/nose/suite.py", line 209, in run
    self.setUp()
  File "/Users/janeklehr/Development/python-cloudant/venv/lib/python2.7/site-packages/nose/suite.py", line 292, in setUp
    self.setupContext(ancestor)
  File "/Users/janeklehr/Development/python-cloudant/venv/lib/python2.7/site-packages/nose/suite.py", line 315, in setupContext
    try_run(context, names)
  File "/Users/janeklehr/Development/python-cloudant/venv/lib/python2.7/site-packages/nose/util.py", line 471, in try_run
    return func()
  File "/Users/janeklehr/Development/python-cloudant/tests/unit/db/unit_t_db_base.py", line 87, in setUpClass
    data='"{0}"'.format(os.environ['DB_PASSWORD'])
  File "/Users/janeklehr/Development/python-cloudant/venv/lib/python2.7/site-packages/requests/api.py", line 120, in put
    return request('put', url, data=data, **kwargs)
  File "/Users/janeklehr/Development/python-cloudant/venv/lib/python2.7/site-packages/requests/api.py", line 53, in request
    return session.request(method=method, url=url, **kwargs)
  File "/Users/janeklehr/Development/python-cloudant/venv/lib/python2.7/site-packages/requests/sessions.py", line 468, in request
    resp = self.send(prep, **send_kwargs)
  File "/Users/janeklehr/Development/python-cloudant/venv/lib/python2.7/site-packages/requests/sessions.py", line 576, in send
    r = adapter.send(request, **kwargs)
  File "/Users/janeklehr/Development/python-cloudant/venv/lib/python2.7/site-packages/requests/adapters.py", line 437, in send
    raise ConnectionError(e, request=request)
ConnectionError: HTTPConnectionPool(host='127.0.0.1', port=5984): Max retries exceeded with url: /_config/admins/unit-test-user-f1a22d76-98b7-4e3c-9c58-5f6cca142a73 (Caused by NewConnectionError('<requests.packages.urllib3.connection.HTTPConnection object at 0x1013e4ed0>: Failed to establish a new connection: [Errno 61] Connection refused',))
-------------------- >> begin captured logging << --------------------
requests.packages.urllib3.connectionpool: INFO: Starting new HTTP connection (1): 127.0.0.1
--------------------- >> end captured logging << ---------------------```

**Comment by alfinkel** [comment]
The unit tests found in the /unit/db folder are indeed making real connections to a database.  They actually can either be executed against just a local CouchDB instance which will skip a bunch of Cloudant specific tests (I think around 85 or so) or if you set your environment variables for your terminal session as is described [here](https://github.com/cloudant/python-cloudant/blob/master/tests/unit/db/unit_t_db_base.py#L22) then the tests will run against the Cloudant instance that you specified.  My recommendation would be to run the tests against a Cloudant instance since your are specifically writing code against Cloudant specific functionality (Cloudant Query does not exist in CouchDB).  In either case you would invoke the test from the command line while at the root folder for the project as is described in the [travis.yml](https://github.com/cloudant/python-cloudant/blob/master/.travis.yml#L11).  Hope that helps.  If you still have problems feel free to ping me on SameTime or Slack and we can walk through the process.
